/**
 * generated by Xtext 2.28.0
 */
package br.edu.unijui.gca.jabuti.provider;


import br.edu.unijui.gca.jabuti.JabutiFactory;
import br.edu.unijui.gca.jabuti.JabutiPackage;
import br.edu.unijui.gca.jabuti.OnBreach;

import java.util.Collection;
import java.util.List;

import org.eclipse.emf.common.notify.AdapterFactory;
import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.common.util.ResourceLocator;

import org.eclipse.emf.ecore.EStructuralFeature;

import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertyDescriptor;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;
import org.eclipse.emf.edit.provider.ItemProviderAdapter;
import org.eclipse.emf.edit.provider.ViewerNotification;

/**
 * This is the item provider adapter for a {@link br.edu.unijui.gca.jabuti.OnBreach} object.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class OnBreachItemProvider 
	extends ItemProviderAdapter
	implements
		IEditingDomainItemProvider,
		IStructuredItemContentProvider,
		ITreeItemContentProvider,
		IItemLabelProvider,
		IItemPropertySource {
	/**
	 * This constructs an instance from a factory and a notifier.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public OnBreachItemProvider(AdapterFactory adapterFactory) {
		super(adapterFactory);
	}

	/**
	 * This returns the property descriptors for the adapted class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public List<IItemPropertyDescriptor> getPropertyDescriptors(Object object) {
		if (itemPropertyDescriptors == null) {
			super.getPropertyDescriptors(object);

		}
		return itemPropertyDescriptors;
	}

	/**
	 * This specifies how to implement {@link #getChildren} and is used to deduce an appropriate feature for an
	 * {@link org.eclipse.emf.edit.command.AddCommand}, {@link org.eclipse.emf.edit.command.RemoveCommand} or
	 * {@link org.eclipse.emf.edit.command.MoveCommand} in {@link #createCommand}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Collection<? extends EStructuralFeature> getChildrenFeatures(Object object) {
		if (childrenFeatures == null) {
			super.getChildrenFeatures(object);
			childrenFeatures.add(JabutiPackage.Literals.ON_BREACH__ACTION);
			childrenFeatures.add(JabutiPackage.Literals.ON_BREACH__MESSAGE);
		}
		return childrenFeatures;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected EStructuralFeature getChildFeature(Object object, Object child) {
		// Check the type of the specified child object and return the proper feature to use for
		// adding (see {@link AddCommand}) it as a child.

		return super.getChildFeature(object, child);
	}

	/**
	 * This returns OnBreach.gif.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object getImage(Object object) {
		return overlayImage(object, getResourceLocator().getImage("full/obj16/OnBreach"));
	}

	/**
	 * This returns the label text for the adapted class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String getText(Object object) {
		return getString("_UI_OnBreach_type");
	}


	/**
	 * This handles model notifications by calling {@link #updateChildren} to update any cached
	 * children and by creating a viewer notification, which it passes to {@link #fireNotifyChanged}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void notifyChanged(Notification notification) {
		updateChildren(notification);

		switch (notification.getFeatureID(OnBreach.class)) {
			case JabutiPackage.ON_BREACH__ACTION:
			case JabutiPackage.ON_BREACH__MESSAGE:
				fireNotifyChanged(new ViewerNotification(notification, notification.getNotifier(), true, false));
				return;
		}
		super.notifyChanged(notification);
	}

	/**
	 * This adds {@link org.eclipse.emf.edit.command.CommandParameter}s describing the children
	 * that can be created under this object.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected void collectNewChildDescriptors(Collection<Object> newChildDescriptors, Object object) {
		super.collectNewChildDescriptors(newChildDescriptors, object);

		newChildDescriptors.add
			(createChildParameter
				(JabutiPackage.Literals.ON_BREACH__ACTION,
				 JabutiFactory.eINSTANCE.createAction()));

		newChildDescriptors.add
			(createChildParameter
				(JabutiPackage.Literals.ON_BREACH__ACTION,
				 JabutiFactory.eINSTANCE.createBusinessAction()));

		newChildDescriptors.add
			(createChildParameter
				(JabutiPackage.Literals.ON_BREACH__ACTION,
				 JabutiFactory.eINSTANCE.createEventLog()));

		newChildDescriptors.add
			(createChildParameter
				(JabutiPackage.Literals.ON_BREACH__MESSAGE,
				 JabutiFactory.eINSTANCE.createExpression()));

		newChildDescriptors.add
			(createChildParameter
				(JabutiPackage.Literals.ON_BREACH__MESSAGE,
				 JabutiFactory.eINSTANCE.createBinaryOperator()));

		newChildDescriptors.add
			(createChildParameter
				(JabutiPackage.Literals.ON_BREACH__MESSAGE,
				 JabutiFactory.eINSTANCE.createLiteralValue()));

		newChildDescriptors.add
			(createChildParameter
				(JabutiPackage.Literals.ON_BREACH__MESSAGE,
				 JabutiFactory.eINSTANCE.createNumericValue()));

		newChildDescriptors.add
			(createChildParameter
				(JabutiPackage.Literals.ON_BREACH__MESSAGE,
				 JabutiFactory.eINSTANCE.createStringValue()));

		newChildDescriptors.add
			(createChildParameter
				(JabutiPackage.Literals.ON_BREACH__MESSAGE,
				 JabutiFactory.eINSTANCE.createVariableValue()));

		newChildDescriptors.add
			(createChildParameter
				(JabutiPackage.Literals.ON_BREACH__MESSAGE,
				 JabutiFactory.eINSTANCE.createFunctionCall()));

		newChildDescriptors.add
			(createChildParameter
				(JabutiPackage.Literals.ON_BREACH__MESSAGE,
				 JabutiFactory.eINSTANCE.createUnaryOperator()));
	}

	/**
	 * Return the resource locator for this item provider's resources.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ResourceLocator getResourceLocator() {
		return JabutiEditPlugin.INSTANCE;
	}

}
