/**
 * generated by Xtext 2.28.0
 */
package br.edu.unijui.gca.jabuti;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Business Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see br.edu.unijui.gca.jabuti.JabutiPackage#getBusinessRule()
 * @model
 * @generated
 */
public interface BusinessRule extends Condition
{
} // BusinessRule
