/**
 * generated by Xtext 2.28.0
 */
package br.edu.unijui.gca.jabuti;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Contract</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.edu.unijui.gca.jabuti.Contract#getName <em>Name</em>}</li>
 *   <li>{@link br.edu.unijui.gca.jabuti.Contract#getBeginDate <em>Begin Date</em>}</li>
 *   <li>{@link br.edu.unijui.gca.jabuti.Contract#getDueDate <em>Due Date</em>}</li>
 *   <li>{@link br.edu.unijui.gca.jabuti.Contract#getApplication <em>Application</em>}</li>
 *   <li>{@link br.edu.unijui.gca.jabuti.Contract#getProcess <em>Process</em>}</li>
 *   <li>{@link br.edu.unijui.gca.jabuti.Contract#getVariables <em>Variables</em>}</li>
 *   <li>{@link br.edu.unijui.gca.jabuti.Contract#getClauses <em>Clauses</em>}</li>
 * </ul>
 *
 * @see br.edu.unijui.gca.jabuti.JabutiPackage#getContract()
 * @model
 * @generated
 */
public interface Contract extends EObject
{
  /**
	 * Returns the value of the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Name</em>' attribute.
	 * @see #setName(String)
	 * @see br.edu.unijui.gca.jabuti.JabutiPackage#getContract_Name()
	 * @model
	 * @generated
	 */
  String getName();

  /**
	 * Sets the value of the '{@link br.edu.unijui.gca.jabuti.Contract#getName <em>Name</em>}' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Name</em>' attribute.
	 * @see #getName()
	 * @generated
	 */
  void setName(String value);

  /**
	 * Returns the value of the '<em><b>Begin Date</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Begin Date</em>' containment reference.
	 * @see #setBeginDate(Expression)
	 * @see br.edu.unijui.gca.jabuti.JabutiPackage#getContract_BeginDate()
	 * @model containment="true"
	 * @generated
	 */
  Expression getBeginDate();

  /**
	 * Sets the value of the '{@link br.edu.unijui.gca.jabuti.Contract#getBeginDate <em>Begin Date</em>}' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Begin Date</em>' containment reference.
	 * @see #getBeginDate()
	 * @generated
	 */
  void setBeginDate(Expression value);

  /**
	 * Returns the value of the '<em><b>Due Date</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Due Date</em>' containment reference.
	 * @see #setDueDate(Expression)
	 * @see br.edu.unijui.gca.jabuti.JabutiPackage#getContract_DueDate()
	 * @model containment="true"
	 * @generated
	 */
  Expression getDueDate();

  /**
	 * Sets the value of the '{@link br.edu.unijui.gca.jabuti.Contract#getDueDate <em>Due Date</em>}' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Due Date</em>' containment reference.
	 * @see #getDueDate()
	 * @generated
	 */
  void setDueDate(Expression value);

  /**
	 * Returns the value of the '<em><b>Application</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Application</em>' containment reference.
	 * @see #setApplication(Application)
	 * @see br.edu.unijui.gca.jabuti.JabutiPackage#getContract_Application()
	 * @model containment="true"
	 * @generated
	 */
  Application getApplication();

  /**
	 * Sets the value of the '{@link br.edu.unijui.gca.jabuti.Contract#getApplication <em>Application</em>}' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Application</em>' containment reference.
	 * @see #getApplication()
	 * @generated
	 */
  void setApplication(Application value);

  /**
	 * Returns the value of the '<em><b>Process</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Process</em>' containment reference.
	 * @see #setProcess(br.edu.unijui.gca.jabuti.Process)
	 * @see br.edu.unijui.gca.jabuti.JabutiPackage#getContract_Process()
	 * @model containment="true"
	 * @generated
	 */
  br.edu.unijui.gca.jabuti.Process getProcess();

  /**
	 * Sets the value of the '{@link br.edu.unijui.gca.jabuti.Contract#getProcess <em>Process</em>}' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Process</em>' containment reference.
	 * @see #getProcess()
	 * @generated
	 */
  void setProcess(br.edu.unijui.gca.jabuti.Process value);

  /**
	 * Returns the value of the '<em><b>Variables</b></em>' containment reference list.
	 * The list contents are of type {@link br.edu.unijui.gca.jabuti.Variable}.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Variables</em>' containment reference list.
	 * @see br.edu.unijui.gca.jabuti.JabutiPackage#getContract_Variables()
	 * @model containment="true"
	 * @generated
	 */
  EList<Variable> getVariables();

  /**
	 * Returns the value of the '<em><b>Clauses</b></em>' containment reference list.
	 * The list contents are of type {@link br.edu.unijui.gca.jabuti.Clause}.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Clauses</em>' containment reference list.
	 * @see br.edu.unijui.gca.jabuti.JabutiPackage#getContract_Clauses()
	 * @model containment="true"
	 * @generated
	 */
  EList<Clause> getClauses();

} // Contract
