/**
 * generated by Xtext 2.25.0
 */
package br.edu.unijui.gca.smartce.smartCE;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Single Variable</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.edu.unijui.gca.smartce.smartCE.SingleVariable#getName <em>Name</em>}</li>
 *   <li>{@link br.edu.unijui.gca.smartce.smartCE.SingleVariable#getValueAndDescription <em>Value And Description</em>}</li>
 * </ul>
 *
 * @see br.edu.unijui.gca.smartce.smartCE.SmartCEPackage#getSingleVariable()
 * @model
 * @generated
 */
public interface SingleVariable extends EObject
{
	/**
	 * Returns the value of the '<em><b>Name</b></em>' attribute.
	 * The default value is <code>"EString"</code>.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Name</em>' attribute.
	 * @see #setName(String)
	 * @see br.edu.unijui.gca.smartce.smartCE.SmartCEPackage#getSingleVariable_Name()
	 * @model default="EString"
	 * @generated
	 */
	String getName();

	/**
	 * Sets the value of the '{@link br.edu.unijui.gca.smartce.smartCE.SingleVariable#getName <em>Name</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Name</em>' attribute.
	 * @see #getName()
	 * @generated
	 */
	void setName(String value);

	/**
	 * Returns the value of the '<em><b>Value And Description</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Value And Description</em>' containment reference.
	 * @see #setValueAndDescription(ValueAndDescription)
	 * @see br.edu.unijui.gca.smartce.smartCE.SmartCEPackage#getSingleVariable_ValueAndDescription()
	 * @model containment="true" required="true"
	 * @generated
	 */
	ValueAndDescription getValueAndDescription();

	/**
	 * Sets the value of the '{@link br.edu.unijui.gca.smartce.smartCE.SingleVariable#getValueAndDescription <em>Value And Description</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Value And Description</em>' containment reference.
	 * @see #getValueAndDescription()
	 * @generated
	 */
	void setValueAndDescription(ValueAndDescription value);

} // SingleVariable
