/**
 * generated by Xtext 2.25.0
 */
package br.edu.unijui.gca.smartce.smartCE;

import java.util.Date;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Status</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.edu.unijui.gca.smartce.smartCE.Status#isActive <em>Active</em>}</li>
 *   <li>{@link br.edu.unijui.gca.smartce.smartCE.Status#isRunning <em>Running</em>}</li>
 *   <li>{@link br.edu.unijui.gca.smartce.smartCE.Status#getCurrentClause <em>Current Clause</em>}</li>
 *   <li>{@link br.edu.unijui.gca.smartce.smartCE.Status#getRemainingTime <em>Remaining Time</em>}</li>
 * </ul>
 *
 * @see br.edu.unijui.gca.smartce.smartCE.SmartCEPackage#getStatus()
 * @model
 * @generated
 */
public interface Status extends EObject
{
	/**
	 * Returns the value of the '<em><b>Active</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Active</em>' attribute.
	 * @see #setActive(boolean)
	 * @see br.edu.unijui.gca.smartce.smartCE.SmartCEPackage#getStatus_Active()
	 * @model
	 * @generated
	 */
	boolean isActive();

	/**
	 * Sets the value of the '{@link br.edu.unijui.gca.smartce.smartCE.Status#isActive <em>Active</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Active</em>' attribute.
	 * @see #isActive()
	 * @generated
	 */
	void setActive(boolean value);

	/**
	 * Returns the value of the '<em><b>Running</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Running</em>' attribute.
	 * @see #setRunning(boolean)
	 * @see br.edu.unijui.gca.smartce.smartCE.SmartCEPackage#getStatus_Running()
	 * @model
	 * @generated
	 */
	boolean isRunning();

	/**
	 * Sets the value of the '{@link br.edu.unijui.gca.smartce.smartCE.Status#isRunning <em>Running</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Running</em>' attribute.
	 * @see #isRunning()
	 * @generated
	 */
	void setRunning(boolean value);

	/**
	 * Returns the value of the '<em><b>Current Clause</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Current Clause</em>' attribute.
	 * @see #setCurrentClause(int)
	 * @see br.edu.unijui.gca.smartce.smartCE.SmartCEPackage#getStatus_CurrentClause()
	 * @model
	 * @generated
	 */
	int getCurrentClause();

	/**
	 * Sets the value of the '{@link br.edu.unijui.gca.smartce.smartCE.Status#getCurrentClause <em>Current Clause</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Current Clause</em>' attribute.
	 * @see #getCurrentClause()
	 * @generated
	 */
	void setCurrentClause(int value);

	/**
	 * Returns the value of the '<em><b>Remaining Time</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Remaining Time</em>' attribute.
	 * @see #setRemainingTime(Date)
	 * @see br.edu.unijui.gca.smartce.smartCE.SmartCEPackage#getStatus_RemainingTime()
	 * @model
	 * @generated
	 */
	Date getRemainingTime();

	/**
	 * Sets the value of the '{@link br.edu.unijui.gca.smartce.smartCE.Status#getRemainingTime <em>Remaining Time</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Remaining Time</em>' attribute.
	 * @see #getRemainingTime()
	 * @generated
	 */
	void setRemainingTime(Date value);

} // Status
