/**
 * generated by Xtext 2.28.0
 */
package br.edu.unijui.gca.jabuti.tests;

import br.edu.unijui.gca.jabuti.JabutiFactory;
import br.edu.unijui.gca.jabuti.OperationLimit;

import junit.textui.TestRunner;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Operation Limit</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class OperationLimitTest extends BusinessRuleTest {

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(OperationLimitTest.class);
	}

	/**
	 * Constructs a new Operation Limit test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public OperationLimitTest(String name) {
		super(name);
	}

	/**
	 * Returns the fixture for this Operation Limit test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected OperationLimit getFixture() {
		return (OperationLimit)fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(JabutiFactory.eINSTANCE.createOperationLimit());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //OperationLimitTest
